version: "3"

networks:
  net_db:
    external: true

services:

  db_test:
    image: postgres:12-alpine
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: first_db
      POSTGRES_LOG_FILE: /var/log/postgres.log
    ports:
      - 6432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d first_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - net_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
